# Generated by Django 6.0.1 on 2026-01-21 13:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ism')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200, verbose_name='Muassasa')),
                ('degree', models.CharField(max_length=200, verbose_name='Daraja/Soha')),
                ('start_date', models.CharField(max_length=100, verbose_name='Boshlanish vaqti')),
                ('end_date', models.CharField(max_length=100, verbose_name='Tugash vaqti')),
            ],
            options={
                'verbose_name': "Ta'lim",
                'verbose_name_plural': "Ta'lim",
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='Kompaniya')),
                ('position', models.CharField(max_length=200, verbose_name='Lavozim')),
                ('start_date', models.CharField(max_length=100, verbose_name='Boshlanish vaqti')),
                ('end_date', models.CharField(default='Hozirgacha', max_length=100, verbose_name='Tugash vaqti')),
                ('description', models.TextField(verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Tajriba',
                'verbose_name_plural': 'Tajribalar',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name="To'liq ism")),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha (masalan: Full Stack Developer)')),
                ('short_intro', models.TextField(verbose_name='Qisqa tanishtiruv')),
                ('about_me', ckeditor.fields.RichTextField(verbose_name="Men haqimda (to'liq)")),
                ('image', models.ImageField(upload_to='profile/', verbose_name='Profil rasmi')),
                ('github', models.URLField(blank=True, null=True, verbose_name='GitHub link')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram link')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn link')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/', verbose_name='Rezyume (PDF)')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profil',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Loyiha nomi')),
                ('description', models.TextField(verbose_name='Qisqa tavsif')),
                ('technologies', models.CharField(max_length=200, verbose_name='Texnologiyalar (vergul bilan ajrating)')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Loyiha rasmi')),
                ('link', models.URLField(verbose_name='Loyiha Havolasi')),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Xizmat nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('icon_class', models.CharField(default='fas fa-code', max_length=100, verbose_name='FontAwesome klassi (masalan: fas fa-code)')),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ko'nikma nomi")),
                ('percentage', models.IntegerField(default=80, verbose_name='Foiz (0-100)')),
            ],
            options={
                'verbose_name': "Ko'nikma",
                'verbose_name_plural': "Ko'nikmalar",
            },
        ),
    ]
